// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  PaperPositionInput,
  PaperOrderUpdate,
} from "./types";

export default {
  jobId: __t.u64(),
  attempt: __t.u32(),
  revision: __t.u64(),
  providerAccountId: __t.string(),
  cashMicros: __t.i64(),
  equityMicros: __t.i64(),
  buyingPowerMicros: __t.i64(),
  currency: __t.string(),
  providerTime: __t.timestamp(),
  marketOpen: __t.bool(),
  nextOpen: __t.option(__t.timestamp()),
  nextClose: __t.option(__t.timestamp()),
  get positions() {
    return __t.array(PaperPositionInput);
  },
  get orders() {
    return __t.array(PaperOrderUpdate);
  },
};
