// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  ticker: __t.string(),
  side: __t.string(),
  quantityMicros: __t.option(__t.i64()),
  notionalMicros: __t.option(__t.i64()),
  clientOrderKey: __t.string(),
  quoteMicros: __t.i64(),
  quoteTime: __t.timestamp(),
};
