// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  ticker: __t.string().primaryKey(),
  generation: __t.u64(),
  priceMicros: __t.i64().name("price_micros"),
  previousCloseMicros: __t.i64().name("previous_close_micros"),
  openMicros: __t.i64().name("open_micros"),
  highMicros: __t.i64().name("high_micros"),
  lowMicros: __t.i64().name("low_micros"),
  providerTime: __t.timestamp().name("provider_time"),
  ingestedAt: __t.timestamp().name("ingested_at"),
  publishedAt: __t.timestamp().name("published_at"),
  source: __t.string(),
});
