// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  discoveryId: __t.u64().name("discovery_id"),
  owner: __t.identity(),
  discoveryDate: __t.string().name("discovery_date"),
  ticker: __t.string(),
  rank: __t.u16(),
  score: __t.f64(),
  trendScore: __t.option(__t.f64()).name("trend_score"),
  fitScore: __t.option(__t.f64()).name("fit_score"),
  newsScore: __t.option(__t.f64()).name("news_score"),
  momentumScore: __t.option(__t.f64()).name("momentum_score"),
  noveltyScore: __t.f64().name("novelty_score"),
  angle: __t.string(),
  about: __t.string(),
  reasons: __t.array(__t.string()),
  newsCount: __t.u16().name("news_count"),
  newsHeadline: __t.option(__t.string()).name("news_headline"),
  newsSource: __t.option(__t.string()).name("news_source"),
  newsUrl: __t.option(__t.string()).name("news_url"),
  newsPublishedAt: __t.option(__t.timestamp()).name("news_published_at"),
  newsClassification: __t.string().name("news_classification"),
});
