// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  owner: __t.identity().primaryKey(),
  generation: __t.u64(),
  jobId: __t.u64().name("job_id"),
  status: __t.string(),
  profileVersion: __t.u32().name("profile_version"),
  profileSchemaVersion: __t.u16().name("profile_schema_version"),
  marketGeneration: __t.u64().name("market_generation"),
  signalAlgorithmVersion: __t.string().name("signal_algorithm_version"),
  fitAlgorithmVersion: __t.string().name("fit_algorithm_version"),
  signalSessionDate: __t.string().name("signal_session_date"),
  consideredCount: __t.u16().name("considered_count"),
  eligibleCount: __t.u16().name("eligible_count"),
  publishedCount: __t.u16().name("published_count"),
  summary: __t.string(),
  limitations: __t.array(__t.string()),
  publishedAt: __t.timestamp().name("published_at"),
});
