// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  DiscoveryItemInput,
} from "./types";

export default {
  jobId: __t.u64(),
  attempt: __t.u32(),
  discoveryDate: __t.string(),
  zodiacSign: __t.option(__t.string()),
  sectorId: __t.string(),
  sectorName: __t.string(),
  subthemeId: __t.string(),
  title: __t.string(),
  description: __t.string(),
  algorithmVersion: __t.string(),
  themeVersion: __t.string(),
  marketGeneration: __t.u64(),
  consideredCount: __t.u16(),
  eligibleCount: __t.u16(),
  get items() {
    return __t.array(DiscoveryItemInput);
  },
};
