// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  SignalFeature,
} from "./types";


export default __t.row({
  ticker: __t.string().primaryKey(),
  generation: __t.u64(),
  algorithmVersion: __t.string().name("algorithm_version"),
  sessionDate: __t.string().name("session_date"),
  status: __t.string(),
  trendScore: __t.option(__t.f64()).name("trend_score"),
  composite: __t.option(__t.f64()),
  coverage: __t.f64(),
  coverageScope: __t.string().name("coverage_scope"),
  benchmark: __t.string(),
  historySessions: __t.u32().name("history_sessions"),
  requiredSessions: __t.u32().name("required_sessions"),
  dayReturn: __t.option(__t.f64()).name("day_return"),
  benchmarkDayReturn: __t.option(__t.f64()).name("benchmark_day_return"),
  relativeDayReturn: __t.option(__t.f64()).name("relative_day_return"),
  get features() {
    return __t.array(SignalFeature);
  },
  notes: __t.array(__t.string()),
  asOf: __t.timestamp().name("as_of"),
  publishedAt: __t.timestamp().name("published_at"),
});
