// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AssistantMessage = __t.object("AssistantMessage", {
  id: __t.u64(),
  owner: __t.identity(),
  sequence: __t.u32(),
  role: __t.string(),
  kind: __t.string(),
  body: __t.string(),
  citations: __t.string(),
  status: __t.string(),
  clientKey: __t.string(),
  createdAt: __t.timestamp(),
});
export type AssistantMessage = __Infer<typeof AssistantMessage>;

export const BarInput = __t.object("BarInput", {
  ticker: __t.string(),
  sessionDate: __t.string(),
  openMicros: __t.option(__t.i64()),
  highMicros: __t.option(__t.i64()),
  lowMicros: __t.option(__t.i64()),
  closeMicros: __t.i64(),
  volume: __t.option(__t.u64()),
  adjusted: __t.bool(),
  source: __t.string(),
});
export type BarInput = __Infer<typeof BarInput>;

export const CapabilityInput = __t.object("CapabilityInput", {
  key: __t.string(),
  provider: __t.string(),
  capability: __t.string(),
  available: __t.bool(),
  detail: __t.string(),
});
export type CapabilityInput = __Infer<typeof CapabilityInput>;

export const DailyBar = __t.object("DailyBar", {
  id: __t.u64(),
  ticker: __t.string(),
  sessionDate: __t.string(),
  openMicros: __t.option(__t.i64()),
  highMicros: __t.option(__t.i64()),
  lowMicros: __t.option(__t.i64()),
  closeMicros: __t.i64(),
  volume: __t.option(__t.u64()),
  adjusted: __t.bool(),
  source: __t.string(),
  ingestedAt: __t.timestamp(),
});
export type DailyBar = __Infer<typeof DailyBar>;

export const DailyDiscovery = __t.object("DailyDiscovery", {
  id: __t.u64(),
  owner: __t.identity(),
  discoveryDate: __t.string(),
  zodiacSign: __t.option(__t.string()),
  sectorId: __t.string(),
  sectorName: __t.string(),
  subthemeId: __t.string(),
  title: __t.string(),
  description: __t.string(),
  algorithmVersion: __t.string(),
  themeVersion: __t.string(),
  marketGeneration: __t.u64(),
  consideredCount: __t.u16(),
  eligibleCount: __t.u16(),
  jobId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type DailyDiscovery = __Infer<typeof DailyDiscovery>;

export const DailyDiscoveryItem = __t.object("DailyDiscoveryItem", {
  id: __t.u64(),
  discoveryId: __t.u64(),
  owner: __t.identity(),
  discoveryDate: __t.string(),
  ticker: __t.string(),
  rank: __t.u16(),
  score: __t.f64(),
  trendScore: __t.option(__t.f64()),
  fitScore: __t.option(__t.f64()),
  newsScore: __t.option(__t.f64()),
  momentumScore: __t.option(__t.f64()),
  noveltyScore: __t.f64(),
  angle: __t.string(),
  about: __t.string(),
  reasons: __t.array(__t.string()),
  newsCount: __t.u16(),
  newsHeadline: __t.option(__t.string()),
  newsSource: __t.option(__t.string()),
  newsUrl: __t.option(__t.string()),
  newsPublishedAt: __t.option(__t.timestamp()),
});
export type DailyDiscoveryItem = __Infer<typeof DailyDiscoveryItem>;

export const DiscoveryItemInput = __t.object("DiscoveryItemInput", {
  ticker: __t.string(),
  rank: __t.u16(),
  score: __t.f64(),
  trendScore: __t.option(__t.f64()),
  fitScore: __t.option(__t.f64()),
  newsScore: __t.option(__t.f64()),
  momentumScore: __t.option(__t.f64()),
  noveltyScore: __t.f64(),
  angle: __t.string(),
  about: __t.string(),
  reasons: __t.array(__t.string()),
  newsCount: __t.u16(),
  newsHeadline: __t.option(__t.string()),
  newsSource: __t.option(__t.string()),
  newsUrl: __t.option(__t.string()),
  newsPublishedAt: __t.option(__t.timestamp()),
});
export type DiscoveryItemInput = __Infer<typeof DiscoveryItemInput>;

export const FitComponent = __t.object("FitComponent", {
  name: __t.string(),
  available: __t.bool(),
  value: __t.option(__t.f64()),
  weight: __t.f64(),
  reason: __t.option(__t.string()),
});
export type FitComponent = __Infer<typeof FitComponent>;

export const InvestmentProfile = __t.object("InvestmentProfile", {
  owner: __t.identity(),
  schemaVersion: __t.u16(),
  profileVersion: __t.u32(),
  riskTolerance: __t.string(),
  investmentHorizon: __t.string(),
  investmentStyle: __t.string(),
  sectorInterests: __t.array(__t.string()),
  experienceLevel: __t.string(),
  primaryGoal: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type InvestmentProfile = __Infer<typeof InvestmentProfile>;

export const Job = __t.object("Job", {
  jobId: __t.u64(),
  owner: __t.identity(),
  kind: __t.string(),
  requestKey: __t.string(),
  inputVersion: __t.u32(),
  status: __t.string(),
  attemptCount: __t.u32(),
  maxAttempts: __t.u32(),
  leaseOwner: __t.option(__t.identity()),
  leaseUntil: __t.option(__t.timestamp()),
  availableAt: __t.timestamp(),
  payload: __t.string(),
  resultRef: __t.option(__t.string()),
  errorCode: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Job = __Infer<typeof Job>;

export const MarketClose = __t.object("MarketClose", {
  id: __t.u64(),
  ticker: __t.string(),
  sessionDate: __t.string(),
  closeMicros: __t.i64(),
});
export type MarketClose = __Infer<typeof MarketClose>;

export const MarketCloses = __t.object("MarketCloses", {});
export type MarketCloses = __Infer<typeof MarketCloses>;

export const MarketGeneration = __t.object("MarketGeneration", {
  scope: __t.string(),
  generation: __t.u64(),
  jobId: __t.u64(),
  asOf: __t.timestamp(),
  publishedAt: __t.timestamp(),
  marketOpen: __t.bool(),
  marketSession: __t.string(),
  marketStatusAt: __t.timestamp(),
  lastCompletedSession: __t.string(),
  quoteCount: __t.u32(),
  signalCount: __t.u32(),
  algorithmVersion: __t.string(),
  provider: __t.string(),
});
export type MarketGeneration = __Infer<typeof MarketGeneration>;

export const MarketQuote = __t.object("MarketQuote", {
  ticker: __t.string(),
  generation: __t.u64(),
  priceMicros: __t.i64(),
  previousCloseMicros: __t.i64(),
  openMicros: __t.i64(),
  highMicros: __t.i64(),
  lowMicros: __t.i64(),
  providerTime: __t.timestamp(),
  ingestedAt: __t.timestamp(),
  publishedAt: __t.timestamp(),
  source: __t.string(),
});
export type MarketQuote = __Infer<typeof MarketQuote>;

export const MarketSchedule = __t.object("MarketSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  intervalSeconds: __t.u32(),
});
export type MarketSchedule = __Infer<typeof MarketSchedule>;

export const ModuleAdmin = __t.object("ModuleAdmin", {
  identity: __t.identity(),
  addedAt: __t.timestamp(),
});
export type ModuleAdmin = __Infer<typeof ModuleAdmin>;

export const MyAccount = __t.object("MyAccount", {});
export type MyAccount = __Infer<typeof MyAccount>;

export const MyAssistantMessages = __t.object("MyAssistantMessages", {});
export type MyAssistantMessages = __Infer<typeof MyAssistantMessages>;

export const MyBranding = __t.object("MyBranding", {});
export type MyBranding = __Infer<typeof MyBranding>;

export const MyDailyDiscovery = __t.object("MyDailyDiscovery", {});
export type MyDailyDiscovery = __Infer<typeof MyDailyDiscovery>;

export const MyDiscoveryItems = __t.object("MyDiscoveryItems", {});
export type MyDiscoveryItems = __Infer<typeof MyDiscoveryItems>;

export const MyJobs = __t.object("MyJobs", {});
export type MyJobs = __Infer<typeof MyJobs>;

export const MyNotifications = __t.object("MyNotifications", {});
export type MyNotifications = __Infer<typeof MyNotifications>;

export const MyPaperAccess = __t.object("MyPaperAccess", {});
export type MyPaperAccess = __Infer<typeof MyPaperAccess>;

export const MyPaperAccount = __t.object("MyPaperAccount", {});
export type MyPaperAccount = __Infer<typeof MyPaperAccount>;

export const MyPaperOrders = __t.object("MyPaperOrders", {});
export type MyPaperOrders = __Infer<typeof MyPaperOrders>;

export const MyPaperPositions = __t.object("MyPaperPositions", {});
export type MyPaperPositions = __Infer<typeof MyPaperPositions>;

export const MyProfile = __t.object("MyProfile", {});
export type MyProfile = __Infer<typeof MyProfile>;

export const MyRecommendationGeneration = __t.object("MyRecommendationGeneration", {});
export type MyRecommendationGeneration = __Infer<typeof MyRecommendationGeneration>;

export const MyRecommendations = __t.object("MyRecommendations", {});
export type MyRecommendations = __Infer<typeof MyRecommendations>;

export const MyServiceGrant = __t.object("MyServiceGrant", {});
export type MyServiceGrant = __Infer<typeof MyServiceGrant>;

export const Notification = __t.object("Notification", {
  id: __t.u64(),
  owner: __t.identity(),
  kind: __t.string(),
  title: __t.string(),
  body: __t.string(),
  ticker: __t.option(__t.string()),
  href: __t.option(__t.string()),
  dedupeKey: __t.string(),
  readAt: __t.option(__t.timestamp()),
  createdAt: __t.timestamp(),
});
export type Notification = __Infer<typeof Notification>;

export const PaperAccount = __t.object("PaperAccount", {
  owner: __t.identity(),
  providerAccountId: __t.string(),
  cashMicros: __t.i64(),
  equityMicros: __t.i64(),
  buyingPowerMicros: __t.i64(),
  currency: __t.string(),
  revision: __t.u64(),
  providerTime: __t.timestamp(),
  syncedAt: __t.timestamp(),
  marketOpen: __t.bool(),
  nextOpen: __t.option(__t.timestamp()),
  nextClose: __t.option(__t.timestamp()),
});
export type PaperAccount = __Infer<typeof PaperAccount>;

export const PaperBinding = __t.object("PaperBinding", {
  slot: __t.string(),
  owner: __t.identity(),
  providerAccountId: __t.string(),
  boundAt: __t.timestamp(),
});
export type PaperBinding = __Infer<typeof PaperBinding>;

export const PaperOrder = __t.object("PaperOrder", {
  orderId: __t.u64(),
  owner: __t.identity(),
  clientOrderKey: __t.string(),
  ticker: __t.string(),
  side: __t.string(),
  quantityMicros: __t.option(__t.i64()),
  notionalMicros: __t.option(__t.i64()),
  quoteMicros: __t.i64(),
  quoteTime: __t.timestamp(),
  status: __t.string(),
  providerOrderId: __t.option(__t.string()),
  filledQuantityMicros: __t.i64(),
  filledAvgPriceMicros: __t.option(__t.i64()),
  rejectReason: __t.option(__t.string()),
  revision: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type PaperOrder = __Infer<typeof PaperOrder>;

export const PaperOrderUpdate = __t.object("PaperOrderUpdate", {
  clientOrderKey: __t.string(),
  status: __t.string(),
  providerOrderId: __t.option(__t.string()),
  filledQuantityMicros: __t.i64(),
  filledAvgPriceMicros: __t.option(__t.i64()),
  rejectReason: __t.option(__t.string()),
});
export type PaperOrderUpdate = __Infer<typeof PaperOrderUpdate>;

export const PaperPosition = __t.object("PaperPosition", {
  id: __t.u64(),
  owner: __t.identity(),
  ticker: __t.string(),
  quantityMicros: __t.i64(),
  avgEntryMicros: __t.i64(),
  marketValueMicros: __t.option(__t.i64()),
  unrealizedPlMicros: __t.option(__t.i64()),
  revision: __t.u64(),
});
export type PaperPosition = __Infer<typeof PaperPosition>;

export const PaperPositionInput = __t.object("PaperPositionInput", {
  ticker: __t.string(),
  quantityMicros: __t.i64(),
  avgEntryMicros: __t.i64(),
  marketValueMicros: __t.option(__t.i64()),
  unrealizedPlMicros: __t.option(__t.i64()),
});
export type PaperPositionInput = __Infer<typeof PaperPositionInput>;

export const ProfileBranding = __t.object("ProfileBranding", {
  owner: __t.identity(),
  zodiacSign: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
});
export type ProfileBranding = __Infer<typeof ProfileBranding>;

export const ProviderCapability = __t.object("ProviderCapability", {
  key: __t.string(),
  provider: __t.string(),
  capability: __t.string(),
  available: __t.bool(),
  detail: __t.string(),
  checkedAt: __t.timestamp(),
});
export type ProviderCapability = __Infer<typeof ProviderCapability>;

export const QuoteInput = __t.object("QuoteInput", {
  ticker: __t.string(),
  priceMicros: __t.i64(),
  previousCloseMicros: __t.i64(),
  openMicros: __t.i64(),
  highMicros: __t.i64(),
  lowMicros: __t.i64(),
  providerTime: __t.timestamp(),
  ingestedAt: __t.timestamp(),
  source: __t.string(),
});
export type QuoteInput = __Infer<typeof QuoteInput>;

export const Recommendation = __t.object("Recommendation", {
  id: __t.u64(),
  owner: __t.identity(),
  generation: __t.u64(),
  ticker: __t.string(),
  displayRank: __t.u16(),
  trendScore: __t.f64(),
  fitScore: __t.f64(),
  recommendationRank: __t.f64(),
  fitCoverage: __t.f64(),
  get components() {
    return __t.array(FitComponent);
  },
  realizedVol: __t.option(__t.f64()),
  maxDrawdown: __t.option(__t.f64()),
  volSessions: __t.u32(),
  drawdownSessions: __t.u32(),
  sector: __t.string(),
  benchmark: __t.string(),
  sessionDate: __t.string(),
  historySource: __t.string(),
  matchReason: __t.string(),
  marketActivity: __t.string(),
  riskObservation: __t.string(),
  learningNote: __t.string(),
  limitations: __t.array(__t.string()),
});
export type Recommendation = __Infer<typeof Recommendation>;

export const RecommendationGeneration = __t.object("RecommendationGeneration", {
  owner: __t.identity(),
  generation: __t.u64(),
  jobId: __t.u64(),
  status: __t.string(),
  profileVersion: __t.u32(),
  profileSchemaVersion: __t.u16(),
  marketGeneration: __t.u64(),
  signalAlgorithmVersion: __t.string(),
  fitAlgorithmVersion: __t.string(),
  signalSessionDate: __t.string(),
  consideredCount: __t.u16(),
  eligibleCount: __t.u16(),
  publishedCount: __t.u16(),
  summary: __t.string(),
  limitations: __t.array(__t.string()),
  publishedAt: __t.timestamp(),
});
export type RecommendationGeneration = __Infer<typeof RecommendationGeneration>;

export const RecommendationInput = __t.object("RecommendationInput", {
  ticker: __t.string(),
  displayRank: __t.u16(),
  trendScore: __t.f64(),
  fitScore: __t.f64(),
  recommendationRank: __t.f64(),
  fitCoverage: __t.f64(),
  get components() {
    return __t.array(FitComponent);
  },
  realizedVol: __t.option(__t.f64()),
  maxDrawdown: __t.option(__t.f64()),
  volSessions: __t.u32(),
  drawdownSessions: __t.u32(),
  sector: __t.string(),
  benchmark: __t.string(),
  sessionDate: __t.string(),
  historySource: __t.string(),
  matchReason: __t.string(),
  marketActivity: __t.string(),
  riskObservation: __t.string(),
  learningNote: __t.string(),
  limitations: __t.array(__t.string()),
});
export type RecommendationInput = __Infer<typeof RecommendationInput>;

export const ServiceConfig = __t.object("ServiceConfig", {
  key: __t.string(),
  boolValue: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type ServiceConfig = __Infer<typeof ServiceConfig>;

export const ServiceIdentity = __t.object("ServiceIdentity", {
  identity: __t.identity(),
  label: __t.string(),
  addedAt: __t.timestamp(),
});
export type ServiceIdentity = __Infer<typeof ServiceIdentity>;

export const SignalFeature = __t.object("SignalFeature", {
  name: __t.string(),
  available: __t.bool(),
  raw: __t.option(__t.f64()),
  normalized: __t.option(__t.f64()),
  weight: __t.f64(),
  sampleCount: __t.u32(),
  baselineCount: __t.u32(),
  reason: __t.option(__t.string()),
});
export type SignalFeature = __Infer<typeof SignalFeature>;

export const SignalInput = __t.object("SignalInput", {
  ticker: __t.string(),
  sessionDate: __t.string(),
  status: __t.string(),
  trendScore: __t.option(__t.f64()),
  composite: __t.option(__t.f64()),
  coverage: __t.f64(),
  coverageScope: __t.string(),
  benchmark: __t.string(),
  historySessions: __t.u32(),
  requiredSessions: __t.u32(),
  dayReturn: __t.option(__t.f64()),
  benchmarkDayReturn: __t.option(__t.f64()),
  relativeDayReturn: __t.option(__t.f64()),
  get features() {
    return __t.array(SignalFeature);
  },
  notes: __t.array(__t.string()),
});
export type SignalInput = __Infer<typeof SignalInput>;

export const Stock = __t.object("Stock", {
  ticker: __t.string(),
  name: __t.string(),
  exchange: __t.string(),
  industry: __t.string(),
  sector: __t.string(),
  currency: __t.string(),
  kind: __t.string(),
  benchmark: __t.string(),
  displayOrder: __t.u16(),
  active: __t.bool(),
  updatedAt: __t.timestamp(),
  logoUrl: __t.string(),
});
export type Stock = __Infer<typeof Stock>;

export const StockInput = __t.object("StockInput", {
  ticker: __t.string(),
  name: __t.string(),
  exchange: __t.string(),
  industry: __t.string(),
  sector: __t.string(),
  currency: __t.string(),
  kind: __t.string(),
  benchmark: __t.string(),
  displayOrder: __t.u16(),
  logoUrl: __t.string(),
});
export type StockInput = __Infer<typeof StockInput>;

export const TrendSignal = __t.object("TrendSignal", {
  ticker: __t.string(),
  generation: __t.u64(),
  algorithmVersion: __t.string(),
  sessionDate: __t.string(),
  status: __t.string(),
  trendScore: __t.option(__t.f64()),
  composite: __t.option(__t.f64()),
  coverage: __t.f64(),
  coverageScope: __t.string(),
  benchmark: __t.string(),
  historySessions: __t.u32(),
  requiredSessions: __t.u32(),
  dayReturn: __t.option(__t.f64()),
  benchmarkDayReturn: __t.option(__t.f64()),
  relativeDayReturn: __t.option(__t.f64()),
  get features() {
    return __t.array(SignalFeature);
  },
  notes: __t.array(__t.string()),
  asOf: __t.timestamp(),
  publishedAt: __t.timestamp(),
});
export type TrendSignal = __Infer<typeof TrendSignal>;

export const TrendSignalHistory = __t.object("TrendSignalHistory", {
  id: __t.u64(),
  ticker: __t.string(),
  generation: __t.u64(),
  algorithmVersion: __t.string(),
  sessionDate: __t.string(),
  status: __t.string(),
  trendScore: __t.option(__t.f64()),
  coverage: __t.f64(),
  get features() {
    return __t.array(SignalFeature);
  },
  asOf: __t.timestamp(),
  publishedAt: __t.timestamp(),
});
export type TrendSignalHistory = __Infer<typeof TrendSignalHistory>;

export const UserAccount = __t.object("UserAccount", {
  identity: __t.identity(),
  issuer: __t.string(),
  subject: __t.string(),
  firstSeenAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
});
export type UserAccount = __Infer<typeof UserAccount>;

export const WorkerAssistantMessages = __t.object("WorkerAssistantMessages", {});
export type WorkerAssistantMessages = __Infer<typeof WorkerAssistantMessages>;

export const WorkerAssistantPositions = __t.object("WorkerAssistantPositions", {});
export type WorkerAssistantPositions = __Infer<typeof WorkerAssistantPositions>;

export const WorkerAssistantRecommendations = __t.object("WorkerAssistantRecommendations", {});
export type WorkerAssistantRecommendations = __Infer<typeof WorkerAssistantRecommendations>;

export const WorkerDailyBars = __t.object("WorkerDailyBars", {});
export type WorkerDailyBars = __Infer<typeof WorkerDailyBars>;

export const WorkerDiscoveryHistory = __t.object("WorkerDiscoveryHistory", {});
export type WorkerDiscoveryHistory = __Infer<typeof WorkerDiscoveryHistory>;

export const WorkerDiscoveryItems = __t.object("WorkerDiscoveryItems", {});
export type WorkerDiscoveryItems = __Infer<typeof WorkerDiscoveryItems>;

export const WorkerJobProfiles = __t.object("WorkerJobProfiles", {});
export type WorkerJobProfiles = __Infer<typeof WorkerJobProfiles>;

export const WorkerJobs = __t.object("WorkerJobs", {});
export type WorkerJobs = __Infer<typeof WorkerJobs>;

export const WorkerPaperAccount = __t.object("WorkerPaperAccount", {});
export type WorkerPaperAccount = __Infer<typeof WorkerPaperAccount>;

export const WorkerPaperOrders = __t.object("WorkerPaperOrders", {});
export type WorkerPaperOrders = __Infer<typeof WorkerPaperOrders>;

export const WorkerRegistration = __t.object("WorkerRegistration", {
  identity: __t.identity(),
  kinds: __t.array(__t.string()),
  registeredAt: __t.timestamp(),
});
export type WorkerRegistration = __Infer<typeof WorkerRegistration>;

