// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  expectedVersion: __t.u32(),
  riskTolerance: __t.string(),
  investmentHorizon: __t.string(),
  investmentStyle: __t.string(),
  sectorInterests: __t.array(__t.string()),
  experienceLevel: __t.string(),
  primaryGoal: __t.string(),
  zodiacSign: __t.option(__t.string()),
};
