// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  discoveryDate: __t.string().name("discovery_date"),
  zodiacSign: __t.option(__t.string()).name("zodiac_sign"),
  sectorId: __t.string().name("sector_id"),
  sectorName: __t.string().name("sector_name"),
  subthemeId: __t.string().name("subtheme_id"),
  title: __t.string(),
  description: __t.string(),
  algorithmVersion: __t.string().name("algorithm_version"),
  themeVersion: __t.string().name("theme_version"),
  marketGeneration: __t.u64().name("market_generation"),
  consideredCount: __t.u16().name("considered_count"),
  eligibleCount: __t.u16().name("eligible_count"),
  jobId: __t.u64().name("job_id"),
  createdAt: __t.timestamp().name("created_at"),
});
