// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  owner: __t.identity().primaryKey(),
  providerAccountId: __t.string().name("provider_account_id"),
  cashMicros: __t.i64().name("cash_micros"),
  equityMicros: __t.i64().name("equity_micros"),
  buyingPowerMicros: __t.i64().name("buying_power_micros"),
  currency: __t.string(),
  revision: __t.u64(),
  providerTime: __t.timestamp().name("provider_time"),
  syncedAt: __t.timestamp().name("synced_at"),
  marketOpen: __t.bool().name("market_open"),
  nextOpen: __t.option(__t.timestamp()).name("next_open"),
  nextClose: __t.option(__t.timestamp()).name("next_close"),
});
