// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  ticker: __t.string(),
  sessionDate: __t.string().name("session_date"),
  openMicros: __t.option(__t.i64()).name("open_micros"),
  highMicros: __t.option(__t.i64()).name("high_micros"),
  lowMicros: __t.option(__t.i64()).name("low_micros"),
  closeMicros: __t.i64().name("close_micros"),
  volume: __t.option(__t.u64()),
  adjusted: __t.bool(),
  source: __t.string(),
  ingestedAt: __t.timestamp().name("ingested_at"),
});
