// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  cacheKey: __t.string().primaryKey().name("cache_key"),
  ticker: __t.string(),
  articleId: __t.string().name("article_id"),
  contentHash: __t.string().name("content_hash"),
  classifierVersion: __t.string().name("classifier_version"),
  relevant: __t.bool(),
  relevanceScore: __t.f64().name("relevance_score"),
  eventType: __t.string().name("event_type"),
  sentiment: __t.string(),
  materiality: __t.string(),
  keep: __t.bool(),
  publishedAt: __t.timestamp().name("published_at"),
  classifiedAt: __t.timestamp().name("classified_at"),
  jobId: __t.u64().name("job_id"),
});
