// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  FitComponent,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  generation: __t.u64(),
  ticker: __t.string(),
  displayRank: __t.u16().name("display_rank"),
  trendScore: __t.f64().name("trend_score"),
  fitScore: __t.f64().name("fit_score"),
  recommendationRank: __t.f64().name("recommendation_rank"),
  fitCoverage: __t.f64().name("fit_coverage"),
  get components() {
    return __t.array(FitComponent);
  },
  realizedVol: __t.option(__t.f64()).name("realized_vol"),
  maxDrawdown: __t.option(__t.f64()).name("max_drawdown"),
  volSessions: __t.u32().name("vol_sessions"),
  drawdownSessions: __t.u32().name("drawdown_sessions"),
  sector: __t.string(),
  benchmark: __t.string(),
  sessionDate: __t.string().name("session_date"),
  historySource: __t.string().name("history_source"),
  matchReason: __t.string().name("match_reason"),
  marketActivity: __t.string().name("market_activity"),
  riskObservation: __t.string().name("risk_observation"),
  learningNote: __t.string().name("learning_note"),
  limitations: __t.array(__t.string()),
});
