// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ClaimJobReducer from "../claim_job_reducer";
import CompleteJobReducer from "../complete_job_reducer";
import CompleteOnboardingReducer from "../complete_onboarding_reducer";
import ConfigureMarketScheduleReducer from "../configure_market_schedule_reducer";
import FailJobReducer from "../fail_job_reducer";
import GrantServiceIdentityReducer from "../grant_service_identity_reducer";
import PublishMarketSnapshotReducer from "../publish_market_snapshot_reducer";
import PublishProviderCapabilitiesReducer from "../publish_provider_capabilities_reducer";
import RegisterWorkerReducer from "../register_worker_reducer";
import RequestBackendCheckReducer from "../request_backend_check_reducer";
import RequestMarketIngestReducer from "../request_market_ingest_reducer";
import RevokeServiceIdentityReducer from "../revoke_service_identity_reducer";
import SetServiceFlagReducer from "../set_service_flag_reducer";
import UpdatePreferencesReducer from "../update_preferences_reducer";
import UpsertStocksReducer from "../upsert_stocks_reducer";

export type ClaimJobParams = __Infer<typeof ClaimJobReducer>;
export type CompleteJobParams = __Infer<typeof CompleteJobReducer>;
export type CompleteOnboardingParams = __Infer<typeof CompleteOnboardingReducer>;
export type ConfigureMarketScheduleParams = __Infer<typeof ConfigureMarketScheduleReducer>;
export type FailJobParams = __Infer<typeof FailJobReducer>;
export type GrantServiceIdentityParams = __Infer<typeof GrantServiceIdentityReducer>;
export type PublishMarketSnapshotParams = __Infer<typeof PublishMarketSnapshotReducer>;
export type PublishProviderCapabilitiesParams = __Infer<typeof PublishProviderCapabilitiesReducer>;
export type RegisterWorkerParams = __Infer<typeof RegisterWorkerReducer>;
export type RequestBackendCheckParams = __Infer<typeof RequestBackendCheckReducer>;
export type RequestMarketIngestParams = __Infer<typeof RequestMarketIngestReducer>;
export type RevokeServiceIdentityParams = __Infer<typeof RevokeServiceIdentityReducer>;
export type SetServiceFlagParams = __Infer<typeof SetServiceFlagReducer>;
export type UpdatePreferencesParams = __Infer<typeof UpdatePreferencesReducer>;
export type UpsertStocksParams = __Infer<typeof UpsertStocksReducer>;

