// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ApplyPaperSnapshotReducer from "../apply_paper_snapshot_reducer";
import BindPaperDemoReducer from "../bind_paper_demo_reducer";
import ClaimJobReducer from "../claim_job_reducer";
import ClearAssistantChatReducer from "../clear_assistant_chat_reducer";
import CompleteJobReducer from "../complete_job_reducer";
import CompleteOnboardingReducer from "../complete_onboarding_reducer";
import ConfigureMarketScheduleReducer from "../configure_market_schedule_reducer";
import CreatePaperOrderIntentReducer from "../create_paper_order_intent_reducer";
import EnqueueAssistantMessageReducer from "../enqueue_assistant_message_reducer";
import FailJobReducer from "../fail_job_reducer";
import GrantServiceIdentityReducer from "../grant_service_identity_reducer";
import MarkAllNotificationsReadReducer from "../mark_all_notifications_read_reducer";
import MarkNotificationReadReducer from "../mark_notification_read_reducer";
import PublishAssistantReplyReducer from "../publish_assistant_reply_reducer";
import PublishDailyDiscoveryReducer from "../publish_daily_discovery_reducer";
import PublishMarketSnapshotReducer from "../publish_market_snapshot_reducer";
import PublishProviderCapabilitiesReducer from "../publish_provider_capabilities_reducer";
import PublishRecommendationsReducer from "../publish_recommendations_reducer";
import RebindPaperDemoReducer from "../rebind_paper_demo_reducer";
import RegisterWorkerReducer from "../register_worker_reducer";
import RequestBackendCheckReducer from "../request_backend_check_reducer";
import RequestDailyDiscoveryReducer from "../request_daily_discovery_reducer";
import RequestHomeBriefReducer from "../request_home_brief_reducer";
import RequestMarketIngestReducer from "../request_market_ingest_reducer";
import RequestPaperReconcileReducer from "../request_paper_reconcile_reducer";
import RequestPaperSyncReducer from "../request_paper_sync_reducer";
import RequestRecommendationsReducer from "../request_recommendations_reducer";
import RevokeServiceIdentityReducer from "../revoke_service_identity_reducer";
import SetServiceFlagReducer from "../set_service_flag_reducer";
import UpdatePreferencesReducer from "../update_preferences_reducer";
import UpsertStocksReducer from "../upsert_stocks_reducer";

export type ApplyPaperSnapshotParams = __Infer<typeof ApplyPaperSnapshotReducer>;
export type BindPaperDemoParams = __Infer<typeof BindPaperDemoReducer>;
export type ClaimJobParams = __Infer<typeof ClaimJobReducer>;
export type ClearAssistantChatParams = __Infer<typeof ClearAssistantChatReducer>;
export type CompleteJobParams = __Infer<typeof CompleteJobReducer>;
export type CompleteOnboardingParams = __Infer<typeof CompleteOnboardingReducer>;
export type ConfigureMarketScheduleParams = __Infer<typeof ConfigureMarketScheduleReducer>;
export type CreatePaperOrderIntentParams = __Infer<typeof CreatePaperOrderIntentReducer>;
export type EnqueueAssistantMessageParams = __Infer<typeof EnqueueAssistantMessageReducer>;
export type FailJobParams = __Infer<typeof FailJobReducer>;
export type GrantServiceIdentityParams = __Infer<typeof GrantServiceIdentityReducer>;
export type MarkAllNotificationsReadParams = __Infer<typeof MarkAllNotificationsReadReducer>;
export type MarkNotificationReadParams = __Infer<typeof MarkNotificationReadReducer>;
export type PublishAssistantReplyParams = __Infer<typeof PublishAssistantReplyReducer>;
export type PublishDailyDiscoveryParams = __Infer<typeof PublishDailyDiscoveryReducer>;
export type PublishMarketSnapshotParams = __Infer<typeof PublishMarketSnapshotReducer>;
export type PublishProviderCapabilitiesParams = __Infer<typeof PublishProviderCapabilitiesReducer>;
export type PublishRecommendationsParams = __Infer<typeof PublishRecommendationsReducer>;
export type RebindPaperDemoParams = __Infer<typeof RebindPaperDemoReducer>;
export type RegisterWorkerParams = __Infer<typeof RegisterWorkerReducer>;
export type RequestBackendCheckParams = __Infer<typeof RequestBackendCheckReducer>;
export type RequestDailyDiscoveryParams = __Infer<typeof RequestDailyDiscoveryReducer>;
export type RequestHomeBriefParams = __Infer<typeof RequestHomeBriefReducer>;
export type RequestMarketIngestParams = __Infer<typeof RequestMarketIngestReducer>;
export type RequestPaperReconcileParams = __Infer<typeof RequestPaperReconcileReducer>;
export type RequestPaperSyncParams = __Infer<typeof RequestPaperSyncReducer>;
export type RequestRecommendationsParams = __Infer<typeof RequestRecommendationsReducer>;
export type RevokeServiceIdentityParams = __Infer<typeof RevokeServiceIdentityReducer>;
export type SetServiceFlagParams = __Infer<typeof SetServiceFlagReducer>;
export type UpdatePreferencesParams = __Infer<typeof UpdatePreferencesReducer>;
export type UpsertStocksParams = __Infer<typeof UpsertStocksReducer>;

