// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ClaimJobReducer from "../claim_job_reducer";
import CompleteJobReducer from "../complete_job_reducer";
import CompleteOnboardingReducer from "../complete_onboarding_reducer";
import FailJobReducer from "../fail_job_reducer";
import GrantServiceIdentityReducer from "../grant_service_identity_reducer";
import RequestBackendCheckReducer from "../request_backend_check_reducer";
import RevokeServiceIdentityReducer from "../revoke_service_identity_reducer";
import UpdatePreferencesReducer from "../update_preferences_reducer";

export type ClaimJobParams = __Infer<typeof ClaimJobReducer>;
export type CompleteJobParams = __Infer<typeof CompleteJobReducer>;
export type CompleteOnboardingParams = __Infer<typeof CompleteOnboardingReducer>;
export type FailJobParams = __Infer<typeof FailJobReducer>;
export type GrantServiceIdentityParams = __Infer<typeof GrantServiceIdentityReducer>;
export type RequestBackendCheckParams = __Infer<typeof RequestBackendCheckReducer>;
export type RevokeServiceIdentityParams = __Infer<typeof RevokeServiceIdentityReducer>;
export type UpdatePreferencesParams = __Infer<typeof UpdatePreferencesReducer>;

