// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.2 (commit 58d2a40718c59535fd5c267e836d473298eb84d5).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import ApplyPaperSnapshotReducer from "./apply_paper_snapshot_reducer";
import BindPaperDemoReducer from "./bind_paper_demo_reducer";
import ClaimJobReducer from "./claim_job_reducer";
import CompleteJobReducer from "./complete_job_reducer";
import CompleteOnboardingReducer from "./complete_onboarding_reducer";
import ConfigureMarketScheduleReducer from "./configure_market_schedule_reducer";
import CreatePaperOrderIntentReducer from "./create_paper_order_intent_reducer";
import EnqueueAssistantMessageReducer from "./enqueue_assistant_message_reducer";
import FailJobReducer from "./fail_job_reducer";
import GrantServiceIdentityReducer from "./grant_service_identity_reducer";
import PublishAssistantReplyReducer from "./publish_assistant_reply_reducer";
import PublishMarketSnapshotReducer from "./publish_market_snapshot_reducer";
import PublishProviderCapabilitiesReducer from "./publish_provider_capabilities_reducer";
import PublishRecommendationsReducer from "./publish_recommendations_reducer";
import RebindPaperDemoReducer from "./rebind_paper_demo_reducer";
import RegisterWorkerReducer from "./register_worker_reducer";
import RequestBackendCheckReducer from "./request_backend_check_reducer";
import RequestHomeBriefReducer from "./request_home_brief_reducer";
import RequestMarketIngestReducer from "./request_market_ingest_reducer";
import RequestPaperReconcileReducer from "./request_paper_reconcile_reducer";
import RequestPaperSyncReducer from "./request_paper_sync_reducer";
import RequestRecommendationsReducer from "./request_recommendations_reducer";
import RevokeServiceIdentityReducer from "./revoke_service_identity_reducer";
import SetServiceFlagReducer from "./set_service_flag_reducer";
import UpdatePreferencesReducer from "./update_preferences_reducer";
import UpsertStocksReducer from "./upsert_stocks_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import MarketClosesRow from "./market_closes_table";
import MarketGenerationRow from "./market_generation_table";
import MarketQuoteRow from "./market_quote_table";
import MyAccountRow from "./my_account_table";
import MyAssistantMessagesRow from "./my_assistant_messages_table";
import MyBrandingRow from "./my_branding_table";
import MyJobsRow from "./my_jobs_table";
import MyPaperAccessRow from "./my_paper_access_table";
import MyPaperAccountRow from "./my_paper_account_table";
import MyPaperOrdersRow from "./my_paper_orders_table";
import MyPaperPositionsRow from "./my_paper_positions_table";
import MyProfileRow from "./my_profile_table";
import MyRecommendationGenerationRow from "./my_recommendation_generation_table";
import MyRecommendationsRow from "./my_recommendations_table";
import MyServiceGrantRow from "./my_service_grant_table";
import ProviderCapabilityRow from "./provider_capability_table";
import StockRow from "./stock_table";
import TrendSignalRow from "./trend_signal_table";
import WorkerAssistantMessagesRow from "./worker_assistant_messages_table";
import WorkerAssistantPositionsRow from "./worker_assistant_positions_table";
import WorkerAssistantRecommendationsRow from "./worker_assistant_recommendations_table";
import WorkerDailyBarsRow from "./worker_daily_bars_table";
import WorkerJobProfilesRow from "./worker_job_profiles_table";
import WorkerJobsRow from "./worker_jobs_table";
import WorkerPaperAccountRow from "./worker_paper_account_table";
import WorkerPaperOrdersRow from "./worker_paper_orders_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  marketGeneration: __table({
    name: 'market_generation',
    indexes: [
      { accessor: 'scope', name: 'market_generation_scope_idx_btree', algorithm: 'btree', columns: [
        'scope',
      ] },
    ],
    constraints: [
      { name: 'market_generation_scope_key', constraint: 'unique', columns: ['scope'] },
    ],
  }, MarketGenerationRow),
  marketQuote: __table({
    name: 'market_quote',
    indexes: [
      { accessor: 'ticker', name: 'market_quote_ticker_idx_btree', algorithm: 'btree', columns: [
        'ticker',
      ] },
    ],
    constraints: [
      { name: 'market_quote_ticker_key', constraint: 'unique', columns: ['ticker'] },
    ],
  }, MarketQuoteRow),
  providerCapability: __table({
    name: 'provider_capability',
    indexes: [
      { accessor: 'key', name: 'provider_capability_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'provider_capability_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, ProviderCapabilityRow),
  stock: __table({
    name: 'stock',
    indexes: [
      { accessor: 'active', name: 'stock_active_idx_btree', algorithm: 'btree', columns: [
        'active',
      ] },
      { accessor: 'ticker', name: 'stock_ticker_idx_btree', algorithm: 'btree', columns: [
        'ticker',
      ] },
    ],
    constraints: [
      { name: 'stock_ticker_key', constraint: 'unique', columns: ['ticker'] },
    ],
  }, StockRow),
  trendSignal: __table({
    name: 'trend_signal',
    indexes: [
      { accessor: 'ticker', name: 'trend_signal_ticker_idx_btree', algorithm: 'btree', columns: [
        'ticker',
      ] },
    ],
    constraints: [
      { name: 'trend_signal_ticker_key', constraint: 'unique', columns: ['ticker'] },
    ],
  }, TrendSignalRow),
  marketCloses: __table({
    name: 'market_closes',
    indexes: [
    ],
    constraints: [
    ],
  }, MarketClosesRow),
  myAccount: __table({
    name: 'my_account',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAccountRow),
  myAssistantMessages: __table({
    name: 'my_assistant_messages',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAssistantMessagesRow),
  myBranding: __table({
    name: 'my_branding',
    indexes: [
    ],
    constraints: [
    ],
  }, MyBrandingRow),
  myJobs: __table({
    name: 'my_jobs',
    indexes: [
    ],
    constraints: [
    ],
  }, MyJobsRow),
  myPaperAccess: __table({
    name: 'my_paper_access',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPaperAccessRow),
  myPaperAccount: __table({
    name: 'my_paper_account',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPaperAccountRow),
  myPaperOrders: __table({
    name: 'my_paper_orders',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPaperOrdersRow),
  myPaperPositions: __table({
    name: 'my_paper_positions',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPaperPositionsRow),
  myProfile: __table({
    name: 'my_profile',
    indexes: [
    ],
    constraints: [
    ],
  }, MyProfileRow),
  myRecommendationGeneration: __table({
    name: 'my_recommendation_generation',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRecommendationGenerationRow),
  myRecommendations: __table({
    name: 'my_recommendations',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRecommendationsRow),
  myServiceGrant: __table({
    name: 'my_service_grant',
    indexes: [
    ],
    constraints: [
    ],
  }, MyServiceGrantRow),
  workerAssistantMessages: __table({
    name: 'worker_assistant_messages',
    indexes: [
    ],
    constraints: [
    ],
  }, WorkerAssistantMessagesRow),
  workerAssistantPositions: __table({
    name: 'worker_assistant_positions',
    indexes: [
    ],
    constraints: [
    ],
  }, WorkerAssistantPositionsRow),
  workerAssistantRecommendations: __table({
    name: 'worker_assistant_recommendations',
    indexes: [
    ],
    constraints: [
    ],
  }, WorkerAssistantRecommendationsRow),
  workerDailyBars: __table({
    name: 'worker_daily_bars',
    indexes: [
    ],
    constraints: [
    ],
  }, WorkerDailyBarsRow),
  workerJobProfiles: __table({
    name: 'worker_job_profiles',
    indexes: [
    ],
    constraints: [
    ],
  }, WorkerJobProfilesRow),
  workerJobs: __table({
    name: 'worker_jobs',
    indexes: [
    ],
    constraints: [
    ],
  }, WorkerJobsRow),
  workerPaperAccount: __table({
    name: 'worker_paper_account',
    indexes: [
    ],
    constraints: [
    ],
  }, WorkerPaperAccountRow),
  workerPaperOrders: __table({
    name: 'worker_paper_orders',
    indexes: [
    ],
    constraints: [
    ],
  }, WorkerPaperOrdersRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("apply_paper_snapshot", ApplyPaperSnapshotReducer),
  __reducerSchema("bind_paper_demo", BindPaperDemoReducer),
  __reducerSchema("claim_job", ClaimJobReducer),
  __reducerSchema("complete_job", CompleteJobReducer),
  __reducerSchema("complete_onboarding", CompleteOnboardingReducer),
  __reducerSchema("configure_market_schedule", ConfigureMarketScheduleReducer),
  __reducerSchema("create_paper_order_intent", CreatePaperOrderIntentReducer),
  __reducerSchema("enqueue_assistant_message", EnqueueAssistantMessageReducer),
  __reducerSchema("fail_job", FailJobReducer),
  __reducerSchema("grant_service_identity", GrantServiceIdentityReducer),
  __reducerSchema("publish_assistant_reply", PublishAssistantReplyReducer),
  __reducerSchema("publish_market_snapshot", PublishMarketSnapshotReducer),
  __reducerSchema("publish_provider_capabilities", PublishProviderCapabilitiesReducer),
  __reducerSchema("publish_recommendations", PublishRecommendationsReducer),
  __reducerSchema("rebind_paper_demo", RebindPaperDemoReducer),
  __reducerSchema("register_worker", RegisterWorkerReducer),
  __reducerSchema("request_backend_check", RequestBackendCheckReducer),
  __reducerSchema("request_home_brief", RequestHomeBriefReducer),
  __reducerSchema("request_market_ingest", RequestMarketIngestReducer),
  __reducerSchema("request_paper_reconcile", RequestPaperReconcileReducer),
  __reducerSchema("request_paper_sync", RequestPaperSyncReducer),
  __reducerSchema("request_recommendations", RequestRecommendationsReducer),
  __reducerSchema("revoke_service_identity", RevokeServiceIdentityReducer),
  __reducerSchema("set_service_flag", SetServiceFlagReducer),
  __reducerSchema("update_preferences", UpdatePreferencesReducer),
  __reducerSchema("upsert_stocks", UpsertStocksReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

