// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  scope: __t.string().primaryKey(),
  generation: __t.u64(),
  jobId: __t.u64().name("job_id"),
  asOf: __t.timestamp().name("as_of"),
  publishedAt: __t.timestamp().name("published_at"),
  marketOpen: __t.bool().name("market_open"),
  marketSession: __t.string().name("market_session"),
  marketStatusAt: __t.timestamp().name("market_status_at"),
  lastCompletedSession: __t.string().name("last_completed_session"),
  quoteCount: __t.u32().name("quote_count"),
  signalCount: __t.u32().name("signal_count"),
  algorithmVersion: __t.string().name("algorithm_version"),
  provider: __t.string(),
});
