// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  jobId: __t.u64().primaryKey().name("job_id"),
  owner: __t.identity(),
  kind: __t.string(),
  requestKey: __t.string().name("request_key"),
  inputVersion: __t.u32().name("input_version"),
  status: __t.string(),
  attemptCount: __t.u32().name("attempt_count"),
  maxAttempts: __t.u32().name("max_attempts"),
  leaseOwner: __t.option(__t.identity()).name("lease_owner"),
  leaseUntil: __t.option(__t.timestamp()).name("lease_until"),
  availableAt: __t.timestamp().name("available_at"),
  payload: __t.string(),
  resultRef: __t.option(__t.string()).name("result_ref"),
  errorCode: __t.option(__t.string()).name("error_code"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
