// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  owner: __t.identity().primaryKey(),
  schemaVersion: __t.u16().name("schema_version"),
  profileVersion: __t.u32().name("profile_version"),
  riskTolerance: __t.string().name("risk_tolerance"),
  investmentHorizon: __t.string().name("investment_horizon"),
  investmentStyle: __t.string().name("investment_style"),
  sectorInterests: __t.array(__t.string()).name("sector_interests"),
  experienceLevel: __t.string().name("experience_level"),
  primaryGoal: __t.string().name("primary_goal"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
