// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  StockNewsStory,
} from "./types";

export default {
  jobId: __t.u64(),
  attempt: __t.u32(),
  ticker: __t.string(),
  get stories() {
    return __t.array(StockNewsStory);
  },
  classification: __t.string(),
  classifierVersion: __t.string(),
};
