// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  RecommendationInput,
} from "./types";

export default {
  jobId: __t.u64(),
  attempt: __t.u32(),
  generation: __t.u64(),
  profileVersion: __t.u32(),
  marketGeneration: __t.u64(),
  signalAlgorithmVersion: __t.string(),
  fitAlgorithmVersion: __t.string(),
  signalSessionDate: __t.string(),
  status: __t.string(),
  consideredCount: __t.u16(),
  eligibleCount: __t.u16(),
  summary: __t.string(),
  limitations: __t.array(__t.string()),
  get items() {
    return __t.array(RecommendationInput);
  },
};
