// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  QuoteInput,
  BarInput,
  SignalInput,
} from "./types";

export default {
  jobId: __t.u64(),
  attempt: __t.u32(),
  generation: __t.u64(),
  asOf: __t.timestamp(),
  algorithmVersion: __t.string(),
  provider: __t.string(),
  marketOpen: __t.bool(),
  marketSession: __t.string(),
  marketStatusAt: __t.timestamp(),
  lastCompletedSession: __t.string(),
  get quotes() {
    return __t.array(QuoteInput);
  },
  get bars() {
    return __t.array(BarInput);
  },
  get signals() {
    return __t.array(SignalInput);
  },
};
