// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  ticker: __t.string().primaryKey(),
  name: __t.string(),
  exchange: __t.string(),
  industry: __t.string(),
  sector: __t.string(),
  currency: __t.string(),
  kind: __t.string(),
  benchmark: __t.string(),
  displayOrder: __t.u16().name("display_order"),
  active: __t.bool(),
  updatedAt: __t.timestamp().name("updated_at"),
  logoUrl: __t.string().name("logo_url"),
});
