// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const InvestmentProfile = __t.object("InvestmentProfile", {
  owner: __t.identity(),
  schemaVersion: __t.u16(),
  profileVersion: __t.u32(),
  riskTolerance: __t.string(),
  investmentHorizon: __t.string(),
  investmentStyle: __t.string(),
  sectorInterests: __t.array(__t.string()),
  experienceLevel: __t.string(),
  primaryGoal: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type InvestmentProfile = __Infer<typeof InvestmentProfile>;

export const Job = __t.object("Job", {
  jobId: __t.u64(),
  owner: __t.identity(),
  kind: __t.string(),
  requestKey: __t.string(),
  inputVersion: __t.u32(),
  status: __t.string(),
  attemptCount: __t.u32(),
  maxAttempts: __t.u32(),
  leaseOwner: __t.option(__t.identity()),
  leaseUntil: __t.option(__t.timestamp()),
  availableAt: __t.timestamp(),
  payload: __t.string(),
  resultRef: __t.option(__t.string()),
  errorCode: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Job = __Infer<typeof Job>;

export const ModuleAdmin = __t.object("ModuleAdmin", {
  identity: __t.identity(),
  addedAt: __t.timestamp(),
});
export type ModuleAdmin = __Infer<typeof ModuleAdmin>;

export const MyAccount = __t.object("MyAccount", {});
export type MyAccount = __Infer<typeof MyAccount>;

export const MyBranding = __t.object("MyBranding", {});
export type MyBranding = __Infer<typeof MyBranding>;

export const MyJobs = __t.object("MyJobs", {});
export type MyJobs = __Infer<typeof MyJobs>;

export const MyProfile = __t.object("MyProfile", {});
export type MyProfile = __Infer<typeof MyProfile>;

export const MyServiceGrant = __t.object("MyServiceGrant", {});
export type MyServiceGrant = __Infer<typeof MyServiceGrant>;

export const ProfileBranding = __t.object("ProfileBranding", {
  owner: __t.identity(),
  zodiacSign: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
});
export type ProfileBranding = __Infer<typeof ProfileBranding>;

export const ServiceIdentity = __t.object("ServiceIdentity", {
  identity: __t.identity(),
  label: __t.string(),
  addedAt: __t.timestamp(),
});
export type ServiceIdentity = __Infer<typeof ServiceIdentity>;

export const UserAccount = __t.object("UserAccount", {
  identity: __t.identity(),
  issuer: __t.string(),
  subject: __t.string(),
  firstSeenAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
});
export type UserAccount = __Infer<typeof UserAccount>;

export const WorkerJobProfiles = __t.object("WorkerJobProfiles", {});
export type WorkerJobProfiles = __Infer<typeof WorkerJobProfiles>;

export const WorkerJobs = __t.object("WorkerJobs", {});
export type WorkerJobs = __Infer<typeof WorkerJobs>;

