// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  orderId: __t.u64().primaryKey().name("order_id"),
  owner: __t.identity(),
  clientOrderKey: __t.string().name("client_order_key"),
  ticker: __t.string(),
  side: __t.string(),
  quantityMicros: __t.option(__t.i64()).name("quantity_micros"),
  notionalMicros: __t.option(__t.i64()).name("notional_micros"),
  quoteMicros: __t.i64().name("quote_micros"),
  quoteTime: __t.timestamp().name("quote_time"),
  status: __t.string(),
  providerOrderId: __t.option(__t.string()).name("provider_order_id"),
  filledQuantityMicros: __t.i64().name("filled_quantity_micros"),
  filledAvgPriceMicros: __t.option(__t.i64()).name("filled_avg_price_micros"),
  rejectReason: __t.option(__t.string()).name("reject_reason"),
  revision: __t.u64(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
