// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  sequence: __t.u32(),
  role: __t.string(),
  kind: __t.string(),
  body: __t.string(),
  citations: __t.string(),
  status: __t.string(),
  clientKey: __t.string().name("client_key"),
  createdAt: __t.timestamp().name("created_at"),
});
